# Generated by Django 4.2.7 on 2024-01-30 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0003_alter_video_video_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoMember',
        ),
    ]
